### ISSUE TITLE
Reaching limit when importing

### ISSUE THREAD

**Issue by MosabWadea** [gavinr/github-csv-tools#71] opened 2022-04-26 11:40 UTC
I am trying to import csv with 88 entries
and I got this error after 20 entries:
```
[@octokit/plugin-throttling] `onAbuseLimit()` is deprecated and will be removed in a future release of `@octokit/plugin-throttling`, please use the `onSecondaryRateLimit` handler instead
Abuse detected for request POST /repos/{owner}/{repo}/issues
Error
{ HttpError: You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later.
    at fetch.then (/usr/local/lib/node_modules/github-csv-tools/node_modules/@octokit/request/dist-node/index.js:86:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by macMikey** [comment] 2022-04-26 18:59
Same, or at least it looks similar.
21 issues imported, many, many more remain
```
`onAbuseLimit()` is deprecated and will be removed in a future release of `@octokit/plugin-throttling`, please use the `onSecondaryRateLimit` handler instead
Abuse detected for request POST /repos/{owner}/{repo}/issues
Error
RequestError [HttpError]: You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later.
```

**Comment by macMikey** [comment] 2022-04-26 19:01
FYI, this is a duplicate of #3

**Closed** 2022-04-26 19:05 UTC
